# core/tts_player.py
# ================================================================
#  TTS PLAYER (Commit 4)
#  - Provides a simple blocking audio playback utility
#  - Still no pause/resume/stop logic implemented
#  - API surface (play/pause/resume/stop) is ready for future commits
# ================================================================

import os
import time
import platform
import subprocess


def _simple_play_blocking(audio_path: str):
    """
    Very simple, blocking audio playback.
    - On Linux/Raspberry Pi: uses `aplay` if available
    - On macOS: uses `afplay`
    - On Windows: prints a message (we'll keep playback elsewhere there)
    """

    if not os.path.isfile(audio_path):
        print(f"[TTSPlayer] Audio file does not exist: {audio_path}")
        return

    system = platform.system()

    # Linux / Raspberry Pi → use aplay
    if system == "Linux":
        cmd = ["aplay", "-q", audio_path]
        try:
            subprocess.call(cmd)
        except Exception as e:
            print(f"[TTSPlayer] aplay error: {e}")

    # macOS → afplay
    elif system == "Darwin":
        cmd = ["afplay", audio_path]
        try:
            subprocess.call(cmd)
        except Exception as e:
            print(f"[TTSPlayer] afplay error: {e}")

    # Windows or unknown → no-op for now
    else:
        print(f"[TTSPlayer] Blocking playback not implemented for {system}. File at: {audio_path}")


class TTSPlayer:
    def __init__(self):
        # These will be used in later commits when we add threading + pause/resume
        self._thread = None
        self._is_paused = False
        self._is_stopped = False

    # ------------------------------------------------------------
    # Commit 4: simple blocking playback using OS tools
    # ------------------------------------------------------------
    def play(self, audio_path_or_text):
        """
        For now we expect an audio file path generated by core.tts.speak().

        Future commits may allow:
        - Passing raw text (and internally calling TTS)
        - Non-blocking, threaded playback with pause/resume/stop
        """
        # For Commit 4, we treat the input as a path
        audio_path = audio_path_or_text

        if not isinstance(audio_path, str):
            print("[TTSPlayer] play() expected a file path string.")
            return

        print(f"[TTSPlayer] Playing audio (blocking): {audio_path}")
        _simple_play_blocking(audio_path)

    # ------------------------------------------------------------
    # Future: Pause audio playback
    # ------------------------------------------------------------
    def pause(self):
        print("[TTSPlayer] pause() called (stub - not implemented yet).")

    # ------------------------------------------------------------
    # Future: Resume audio playback
    # ------------------------------------------------------------
    def resume(self):
        print("[TTSPlayer] resume() called (stub - not implemented yet).")

    # ------------------------------------------------------------
    # Future: Stop audio playback immediately
    # ------------------------------------------------------------
    def stop(self):
        print("[TTSPlayer] stop() called (stub - not implemented yet).")


# Global singleton instance
tts = TTSPlayer()
