# core/tts_player.py
# ================================================================
#  TTS PLAYER (Commit 5)
#  - Background threaded playback
#  - Non-blocking play()
#  - Prepares for pause/resume/stop in future commits
# ================================================================

import os
import time
import platform
import subprocess
import threading


def _simple_play_blocking(audio_path: str):
    """
    Blocking audio playback for Linux/macOS using system tools.
    - Linux / Raspberry Pi → aplay
    - macOS → afplay
    - Windows → no-op (future)
    """

    if not os.path.isfile(audio_path):
        print(f"[TTSPlayer] Audio file does not exist: {audio_path}")
        return

    system = platform.system()

    # Linux / Raspberry Pi → ALSA
    if system == "Linux":
        cmd = ["aplay", "-q", audio_path]
        subprocess.call(cmd)

    # macOS
    elif system == "Darwin":
        cmd = ["afplay", audio_path]
        subprocess.call(cmd)

    else:
        print(f"[TTSPlayer] Playback not implemented for {system}. Path: {audio_path}")


class TTSPlayer:
    def __init__(self):
        self._thread = None
        self._is_stopped = False

    # ------------------------------------------------------------
    # Commit 5: threaded playback
    # ------------------------------------------------------------
    def _play_thread(self, audio_path):
        """
        This function runs inside a background thread.
        It uses the simple blocking audio playback internally.
        """
        # If stop flag triggered before thread runs
        if self._is_stopped:
            return

        _simple_play_blocking(audio_path)

        # Playback finished naturally
        self._thread = None

    def play(self, audio_path_or_text):
        """
        Accepts path generated by core.tts.speak()
        Spawns a new playback thread (non-blocking).
        """

        audio_path = audio_path_or_text

        if not isinstance(audio_path, str):
            print("[TTSPlayer] play() expected a file path string.")
            return

        print(f"[TTSPlayer] Starting threaded playback: {audio_path}")

        # If something is currently playing → stop it
        if self._thread and self._thread.is_alive():
            print("[TTSPlayer] Stopping previous audio...")
            self.stop()
            time.sleep(0.1)

        # Reset stop flag
        self._is_stopped = False

        # Spawn new thread
        self._thread = threading.Thread(
            target=self._play_thread,
            args=(audio_path,),
            daemon=True
        )
        self._thread.start()

    # ------------------------------------------------------------
    # Future: Pause audio playback
    # ------------------------------------------------------------
    def pause(self):
        print("[TTSPlayer] pause() called (stub - coming soon).")

    # ------------------------------------------------------------
    # Future: Resume audio playback
    # ------------------------------------------------------------
    def resume(self):
        print("[TTSPlayer] resume() called (stub - coming soon).")

    # ------------------------------------------------------------
    # Commit 5: STOP kills the thread playback
    # ------------------------------------------------------------
    def stop(self):
        """
        Signals the playback thread to stop after the current system
        call finishes. True instant kill isn't available until
        we replace aplay with streaming PCM playback.
        """
        print("[TTSPlayer] stop() called.")
        self._is_stopped = True

        # If thread exists, wait for it to die (best we can do with aplay)
        if self._thread and self._thread.is_alive():
            try:
                # There is no clean way to kill subprocess.call(aplay)
                # Until we switch to PCM streaming in future commits.
                # For now: rely on next play() overriding.
                pass
            except:
                pass

        self._thread = None


# Global singleton
tts = TTSPlayer()
